import { BusinessModuleCode, SearchResultItem } from '../../types';

export interface ClientEstablishment {
  id: string;
  name: string;
  moduleCode: BusinessModuleCode;
  categoryName: string;
  neighborhood: string;
  city: string;
  distanceKm: number;
  rating: number;
  reviewCount: number;
  isVerified: boolean;
  isOpenNow: boolean;
  openHoursText: string;
  phone: string;
  whatsapp: string;
  coverImage: string;
  description: string;
  priceStartingAt: number;
  priceUnitText: string;
  badgeStatus: string;
  services: {
    id: string;
    title: string;
    subtitle: string;
    price: number;
    priceFormatted: string;
    duration?: string;
    isAvailable: boolean;
  }[];
  offers: {
    id: string;
    title: string;
    subtitle: string;
    badge: string;
    discountedPrice: string;
    originalPrice?: string;
  }[];
  photos: string[];
  reviews: {
    id: string;
    author: string;
    avatarColor: string;
    rating: number;
    date: string;
    comment: string;
    isVoice?: boolean;
  }[];
  bookingType: 'nuit' | 'rdv' | 'visite' | 'devis';
}

export const CLIENT_MODULES = [
  {
    id: 'immo',
    name: 'Immobilier',
    short: 'Immobilier',
    code: 'IMMOBILIER' as BusinessModuleCode,
    icon: 'Home',
    bg: 'var(--soft)',
    desc: 'Maisons, appartements, terrains : location et vente',
    feat: 1,
  },
  {
    id: 'guest',
    name: 'Guest House & Hôtellerie',
    short: 'Guest House',
    code: 'GUEST_HOUSE' as BusinessModuleCode,
    icon: 'Bed',
    bg: 'var(--softcyan)',
    desc: 'Chambres, nuitées et séjours près de vous',
    feat: 2,
  },
  {
    id: 'coiffure',
    name: 'Coiffure & Tresses',
    short: 'Coiffure',
    code: 'COIFFURE' as BusinessModuleCode,
    icon: 'Scissors',
    bg: '#FCE9F3',
    desc: 'Tresses, coupes et coiffures sur rendez-vous',
    feat: 3,
  },
  {
    id: 'barbier',
    name: 'Barbier & Grooming',
    short: 'Barbier',
    code: 'BARBIER' as BusinessModuleCode,
    icon: 'Sparkles',
    bg: 'var(--softcyan)',
    desc: 'Taille de barbe, dégradés et soins masculins',
    feat: 4,
  },
  {
    id: 'institut',
    name: 'Institut / Cosmétique',
    short: 'Cosmétique',
    code: 'INSTITUT_COSMETIQUE' as BusinessModuleCode,
    icon: 'HeartHandshake',
    bg: '#FDE8E8',
    desc: 'Soins du visage, onglerie et esthétique',
    feat: 5,
  },
  {
    id: 'spa',
    name: 'Spa & Massage',
    short: 'Spa & Massage',
    code: 'SPA_MASSAGE' as BusinessModuleCode,
    icon: 'Activity',
    bg: '#FCE9F3',
    desc: 'Massages relaxants, hammam et détente',
    feat: 6,
  },
  {
    id: 'photographe',
    name: 'Photographe & Studio',
    short: 'Photographe',
    code: 'PHOTOGRAPHE' as BusinessModuleCode,
    icon: 'Camera',
    bg: 'var(--soft)',
    desc: 'Séances photo studio, événements et tirages',
  },
  {
    id: 'broderie',
    name: 'Broderie & Impression textile',
    short: 'Broderie',
    code: 'BRODERIE_IMPRESSION' as BusinessModuleCode,
    icon: 'Palette',
    bg: 'var(--softcyan)',
    desc: 'Broderie artisanale, flocage et impression textile',
  },
  {
    id: 'garage',
    name: 'Garage & Entretien Auto',
    short: 'Garage',
    code: 'GARAGE' as BusinessModuleCode,
    icon: 'Wrench',
    bg: '#EEE9FD',
    desc: 'Vidange, révision mécanique, freinage et diagnostic auto',
  },
  {
    id: 'pharmacie',
    name: 'Pharmacies & Officines',
    short: 'Pharmacies',
    code: 'PHARMACIE' as BusinessModuleCode,
    icon: 'ShieldCheck',
    bg: '#E8FDF3',
    desc: 'Officines de garde, disponibilité et contact direct',
  },
];

export const CLIENT_ESTABLISHMENTS: ClientEstablishment[] = [
  {
    id: 'biz-palma',
    name: 'Résidence Palma',
    moduleCode: 'GUEST_HOUSE',
    categoryName: "Maison d'hôtes",
    neighborhood: 'Cadjehoun',
    city: 'Cotonou',
    distanceKm: 1.2,
    rating: 4.8,
    reviewCount: 124,
    isVerified: true,
    isOpenNow: true,
    openHoursText: 'Ouvert 24h/24',
    phone: '+229 97 00 00 00',
    whatsapp: '+229 97 00 00 00',
    coverImage: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80',
    description: "Maison d'hôtes calme et propre au cœur de Cotonou. Chambres climatisées, wifi haut débit, petit-déjeuner continental servi dès 6h30. Accueil personnalisé 24h/24.",
    priceStartingAt: 25000,
    priceUnitText: '/ nuit',
    badgeStatus: 'Disponible ce soir',
    bookingType: 'nuit',
    services: [
      {
        id: 'svc-p1',
        title: 'Chambre standard',
        subtitle: 'Clim · Wifi · 1-2 pers.',
        price: 25000,
        priceFormatted: '25 000 FCFA',
        isAvailable: true,
      },
      {
        id: 'svc-p2',
        title: 'Chambre VIP',
        subtitle: 'Clim · Smart TV · Balcon avec vue',
        price: 40000,
        priceFormatted: '40 000 FCFA',
        isAvailable: true,
      },
      {
        id: 'svc-p3',
        title: 'Petit-déjeuner complet',
        subtitle: 'Servi de 6h30 à 10h00',
        price: 3000,
        priceFormatted: '3 000 FCFA',
        isAvailable: true,
      },
      {
        id: 'svc-p4',
        title: 'Navette aéroport',
        subtitle: 'Accueil & transfert privé',
        price: 5000,
        priceFormatted: '5 000 FCFA',
        isAvailable: true,
      },
    ],
    offers: [
      {
        id: 'off-p1',
        title: '2 nuits = petit-déjeuner offert',
        subtitle: "Résidence Palma · Jusqu'au 30 septembre",
        badge: '−20 %',
        discountedPrice: '20 000 FCFA / nuit',
        originalPrice: '25 000 FCFA',
      },
    ],
    photos: [
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800&q=80',
    ],
    reviews: [
      {
        id: 'rev-p1',
        author: 'Aïcha',
        avatarColor: '#E06900',
        rating: 5,
        date: 'il y a 2 jours',
        comment: 'Chambre très propre, accueil chaleureux et personnel attentionné. Je recommande vivement pour vos séjours à Cotonou !',
      },
      {
        id: 'rev-p2',
        author: 'Koffi',
        avatarColor: '#0794A0',
        rating: 4,
        date: 'il y a 1 semaine',
        comment: 'Très bien situé à Cadjehoun, excellent rapport qualité-prix. Literie confortable.',
      },
      {
        id: 'rev-p3',
        author: 'Mariam',
        avatarColor: '#0A9159',
        rating: 5,
        date: 'il y a 3 semaines',
        comment: 'Très bon séjour, personnel souriant et serviable. Tout était parfait.',
        isVoice: true,
      },
    ],
  },
  {
    id: 'biz-haie-vive',
    name: 'Immo Bénin Services — Haie Vive',
    moduleCode: 'IMMOBILIER',
    categoryName: 'Agence immobilière',
    neighborhood: 'Haie Vive',
    city: 'Cotonou',
    distanceKm: 2.5,
    rating: 4.6,
    reviewCount: 38,
    isVerified: true,
    isOpenNow: true,
    openHoursText: 'Ouvert 8h30 - 18h30',
    phone: '+229 97 11 22 33',
    whatsapp: '+229 97 11 22 33',
    coverImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    description: 'Appartements meublés de standing, maisons et bureaux professionnels à louer ou acheter à Cotonou et Abomey-Calavi. Visites accompagnées par nos agents certifiés.',
    priceStartingAt: 120000,
    priceUnitText: '/ mois',
    badgeStatus: 'Visite possible cette semaine',
    bookingType: 'visite',
    services: [
      {
        id: 'svc-i1',
        title: 'Appartement meublé 2 chambres',
        subtitle: 'Haie Vive · Salon climatisé, cuisine équipée',
        price: 120000,
        priceFormatted: '120 000 FCFA',
        isAvailable: true,
      },
      {
        id: 'svc-i2',
        title: 'Maison 3 chambres avec cour',
        subtitle: 'Abomey-Calavi · Quartier résidentiel calme',
        price: 90000,
        priceFormatted: '90 000 FCFA',
        isAvailable: true,
      },
      {
        id: 'svc-i3',
        title: 'Visite guidée sur place',
        subtitle: 'Accompagnement par un conseiller immobilier',
        price: 5000,
        priceFormatted: '5 000 FCFA',
        isAvailable: true,
      },
    ],
    offers: [],
    photos: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    ],
    reviews: [
      {
        id: 'rev-i1',
        author: 'Koffi',
        avatarColor: '#0794A0',
        rating: 4,
        date: 'il y a 1 semaine',
        comment: 'Visite bien organisée, agent ponctuel et sérieux. Le contrat a été expliqué clairement.',
      },
    ],
  },
  {
    id: 'biz-elegance',
    name: 'Salon Élégance & Barber',
    moduleCode: 'COIFFURE',
    categoryName: 'Coiffure & Barber',
    neighborhood: 'Cadjehoun',
    city: 'Cotonou',
    distanceKm: 2.1,
    rating: 4.6,
    reviewCount: 87,
    isVerified: true,
    isOpenNow: true,
    openHoursText: "Ouvert jusqu'à 19h00",
    phone: '+229 97 44 55 66',
    whatsapp: '+229 97 44 55 66',
    coverImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80',
    description: 'Salon mixte professionnel spécialisé en tresses africaines, coupes tendances, dégradés homme, soins capillaires et taille de barbe avec serviette chaude.',
    priceStartingAt: 4000,
    priceUnitText: 'dès 4 000 FCFA',
    badgeStatus: 'Créneaux disponibles demain',
    bookingType: 'rdv',
    services: [
      {
        id: 'svc-c1',
        title: 'Tresses collées modernes',
        subtitle: '≈ 2 h · Finition soignée',
        price: 5000,
        priceFormatted: '5 000 FCFA',
        duration: '2h',
        isAvailable: true,
      },
      {
        id: 'svc-c2',
        title: 'Box braids / Nattes libres',
        subtitle: '≈ 4 h · Mèches non incluses',
        price: 12000,
        priceFormatted: '12 000 FCFA',
        duration: '4h',
        isAvailable: true,
      },
      {
        id: 'svc-c3',
        title: 'Coupe homme + taille de barbe',
        subtitle: '≈ 45 min · Soin hydratant',
        price: 4000,
        priceFormatted: '4 000 FCFA',
        duration: '45m',
        isAvailable: true,
      },
    ],
    offers: [
      {
        id: 'off-c1',
        title: 'Tresses −20 % en semaine',
        subtitle: 'Salon Élégance · Lundi à jeudi de 9h à 14h',
        badge: 'Offre',
        discountedPrice: 'Dès 4 000 FCFA',
      },
    ],
    photos: [
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80',
    ],
    reviews: [
      {
        id: 'rev-c1',
        author: 'Bintou',
        avatarColor: '#0794A0',
        rating: 5,
        date: 'la semaine dernière',
        comment: "Tresses impeccables et à l'heure convenue. Salon propre et accueillant, j'y retourne !",
      },
    ],
  },
  {
    id: 'biz-barbier',
    name: 'Le Barbier Cotonois',
    moduleCode: 'BARBIER',
    categoryName: 'Barbier & Grooming',
    neighborhood: 'Cadjehoun',
    city: 'Cotonou',
    distanceKm: 1.1,
    rating: 4.8,
    reviewCount: 88,
    isVerified: true,
    isOpenNow: true,
    openHoursText: 'Ouvert · Sans ou avec RDV',
    phone: '+229 97 44 55 66',
    whatsapp: '+229 97 44 55 66',
    coverImage: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=80',
    description: 'Salon de barbier moderne et soigné. Dégradé américain, taille de barbe au coupe-chou, serviette chaude et soins du visage pour homme.',
    priceStartingAt: 3000,
    priceUnitText: 'la coupe',
    badgeStatus: 'Créneaux disponibles',
    bookingType: 'rdv',
    services: [
      {
        id: 'svc-b1',
        title: 'Taille de barbe + Serviette chaude',
        subtitle: 'Finitions nettes au rasoir & huile nourrissante',
        price: 3000,
        priceFormatted: '3 000 FCFA',
        duration: '30m',
        isAvailable: true,
      },
      {
        id: 'svc-b2',
        title: 'Coupe homme & Dégradé soigné',
        subtitle: 'Shampoing inclus · Conseils coiffage',
        price: 4000,
        priceFormatted: '4 000 FCFA',
        duration: '40m',
        isAvailable: true,
      },
    ],
    offers: [],
    photos: [
      'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=80',
    ],
    reviews: [
      {
        id: 'rev-b1',
        author: 'Fabrice',
        avatarColor: '#FB8205',
        rating: 5,
        date: 'hier',
        comment: 'Très bon barbier, finitions impeccables et serviette chaude très agréable.',
      },
    ],
  },
  {
    id: 'biz-institut',
    name: 'Institut Sublime Beauté',
    moduleCode: 'INSTITUT_COSMETIQUE',
    categoryName: 'Institut / Cosmétique',
    neighborhood: 'Haie Vive',
    city: 'Cotonou',
    distanceKm: 1.5,
    rating: 4.9,
    reviewCount: 112,
    isVerified: true,
    isOpenNow: true,
    openHoursText: 'Ouvert du mardi au samedi',
    phone: '+229 96 11 22 33',
    whatsapp: '+229 96 11 22 33',
    coverImage: 'https://images.unsplash.com/photo-1560750588-73207b1ef5b8?w=800&q=80',
    description: 'Institut de soins esthétiques, onglerie et vente de cosmétiques certifiés. Soins personnalisés en cabine privée.',
    priceStartingAt: 8000,
    priceUnitText: 'le soin',
    badgeStatus: 'Cabines climatisées',
    bookingType: 'rdv',
    services: [
      {
        id: 'svc-i1',
        title: 'Soin éclat du visage',
        subtitle: 'Nettoyage en profondeur & masque hydratant',
        price: 15000,
        priceFormatted: '15 000 FCFA',
        duration: '60m',
        isAvailable: true,
      },
      {
        id: 'svc-i2',
        title: 'Pose vernis semi-permanent & Manucure',
        subtitle: 'Limage, cuticules et tenue longue durée',
        price: 8000,
        priceFormatted: '8 000 FCFA',
        duration: '45m',
        isAvailable: true,
      },
    ],
    offers: [],
    photos: [
      'https://images.unsplash.com/photo-1560750588-73207b1ef5b8?w=800&q=80',
    ],
    reviews: [
      {
        id: 'rev-i1',
        author: 'Nadège',
        avatarColor: '#0794A0',
        rating: 5,
        date: 'il y a 3 jours',
        comment: 'Onglerie magnifique et soin du visage très doux. Cadre relaxant.',
      },
    ],
  },
  {
    id: 'biz-spa',
    name: 'Oasis Spa & Massage',
    moduleCode: 'SPA_MASSAGE',
    categoryName: 'Spa & Massage',
    neighborhood: 'Fidjrossè',
    city: 'Cotonou',
    distanceKm: 2.8,
    rating: 4.8,
    reviewCount: 76,
    isVerified: true,
    isOpenNow: true,
    openHoursText: 'Ouvert 7j/7 de 10h à 21h',
    phone: '+229 97 12 34 56',
    whatsapp: '+229 97 12 34 56',
    coverImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
    description: 'Espace bien-être dédié à la détente : massages relaxants, rituels corporels aux huiles naturelles, hammam traditionnel et forfaits duo.',
    priceStartingAt: 20000,
    priceUnitText: 'la séance',
    badgeStatus: 'Espace détente',
    bookingType: 'rdv',
    services: [
      {
        id: 'svc-s1',
        title: 'Massage relaxant aux huiles essentielles',
        subtitle: 'Détente musculaire totale · 60 minutes',
        price: 20000,
        priceFormatted: '20 000 FCFA',
        duration: '60m',
        isAvailable: true,
      },
      {
        id: 'svc-s2',
        title: 'Rituel Duo Détente & Hammam',
        subtitle: 'Accès hammam privatif + massage 2 personnes',
        price: 45000,
        priceFormatted: '45 000 FCFA',
        duration: '90m',
        isAvailable: true,
      },
    ],
    offers: [],
    photos: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
    ],
    reviews: [
      {
        id: 'rev-s1',
        author: 'Marc',
        avatarColor: '#FB8205',
        rating: 5,
        date: 'la semaine dernière',
        comment: 'Très belle expérience, massage relaxant parfait après une longue semaine.',
      },
    ],
  },
  {
    id: 'biz-photo',
    name: 'Studio Photo Prestige',
    moduleCode: 'PHOTOGRAPHE',
    categoryName: 'Photographe & Studio',
    neighborhood: 'Haie Vive',
    city: 'Cotonou',
    distanceKm: 1.8,
    rating: 4.9,
    reviewCount: 64,
    isVerified: true,
    isOpenNow: true,
    openHoursText: 'Ouvert du lundi au samedi',
    phone: '+229 97 78 89 90',
    whatsapp: '+229 97 78 89 90',
    coverImage: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&q=80',
    description: 'Shooting photo portrait professionnel en studio climatisé, book photo, séances famille et reportages photo événementiels.',
    priceStartingAt: 15000,
    priceUnitText: 'la séance',
    badgeStatus: 'Studio professionnel',
    bookingType: 'rdv',
    services: [
      {
        id: 'svc-p1',
        title: 'Shooting Portrait Studio (5 photos HD retouchées)',
        subtitle: 'Séance 45 min · Studio climatisé · Livraison numérique',
        price: 15000,
        priceFormatted: '15 000 FCFA',
        duration: '45m',
        isAvailable: true,
      },
      {
        id: 'svc-p2',
        title: 'Shooting Famille / Événement',
        subtitle: 'Séance 1h30 · 15 photos HD retouchées',
        price: 35000,
        priceFormatted: '35 000 FCFA',
        duration: '90m',
        isAvailable: true,
      },
    ],
    offers: [],
    photos: [
      'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&q=80',
    ],
    reviews: [
      {
        id: 'rev-p1',
        author: 'Clarisse',
        avatarColor: '#0794A0',
        rating: 5,
        date: 'il y a 5 jours',
        comment: 'Photos de profil impeccables et éclairage parfait en studio.',
      },
    ],
  },
  {
    id: 'biz-broderie',
    name: 'Atelier Broderie & Flocage Bénin',
    moduleCode: 'BRODERIE_IMPRESSION',
    categoryName: 'Broderie & Impression textile',
    neighborhood: 'Akpakpa',
    city: 'Cotonou',
    distanceKm: 3.2,
    rating: 4.8,
    reviewCount: 92,
    isVerified: true,
    isOpenNow: true,
    openHoursText: 'Ouvert du lundi au samedi dès 8h',
    phone: '+229 96 44 33 22',
    whatsapp: '+229 96 44 33 22',
    coverImage: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80',
    description: 'Atelier spécialisé en broderie informatique, flocage haute précision, sérigraphie et impression sur t-shirts, casquettes et tenues professionnelles.',
    priceStartingAt: 2500,
    priceUnitText: 'sur devis',
    badgeStatus: 'Atelier équipé',
    bookingType: 'devis',
    services: [
      {
        id: 'svc-br1',
        title: 'Broderie logo sur polos / chemises',
        subtitle: 'Broderie numérique haute définition',
        price: 2500,
        priceFormatted: '2 500 FCFA / pièce',
        isAvailable: true,
      },
      {
        id: 'svc-br2',
        title: 'Flocage et impression textile par lot',
        subtitle: 'T-shirts, maillots ou casquettes personnalisés',
        price: 3000,
        priceFormatted: 'Sur devis',
        isAvailable: true,
      },
    ],
    offers: [],
    photos: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80',
    ],
    reviews: [
      {
        id: 'rev-br1',
        author: 'Arnaud',
        avatarColor: '#48576D',
        rating: 5,
        date: 'il y a 6 jours',
        comment: 'Polos d’entreprise brodés avec une excellente précision.',
      },
    ],
  },
  {
    id: 'biz-garage',
    name: 'Garage Mécanique Express',
    moduleCode: 'GARAGE',
    categoryName: 'Garage & Entretien Auto',
    neighborhood: 'Ganhi',
    city: 'Cotonou',
    distanceKm: 2.0,
    rating: 4.7,
    reviewCount: 84,
    isVerified: true,
    isOpenNow: true,
    openHoursText: 'Ouvert 6j/7 dès 7h30',
    phone: '+229 97 55 66 77',
    whatsapp: '+229 97 55 66 77',
    coverImage: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&q=80',
    description: 'Atelier de mécanique et maintenance automobile multi-marques. Vidange moteur express, diagnostic électronique, plaquettes de frein et révision générale.',
    priceStartingAt: 15000,
    priceUnitText: 'sur devis',
    badgeStatus: 'Prise en charge rapide',
    bookingType: 'devis',
    services: [
      {
        id: 'svc-g1',
        title: 'Vidange moteur express + Filtres',
        subtitle: 'Huile de synthèse certifiée · Checkup 15 points offert',
        price: 25000,
        priceFormatted: '25 000 FCFA',
        isAvailable: true,
      },
      {
        id: 'svc-g2',
        title: 'Diagnostic électronique & Freinage',
        subtitle: 'Lecture valise OBD · Contrôle plaquettes et disques',
        price: 15000,
        priceFormatted: '15 000 FCFA',
        isAvailable: true,
      },
    ],
    offers: [],
    photos: [
      'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&q=80',
    ],
    reviews: [
      {
        id: 'rev-g1',
        author: 'Gilles',
        avatarColor: '#FB8205',
        rating: 5,
        date: 'hier',
        comment: 'Vidange rapide et explications claires sur l’état des freins. Très professionnel.',
      },
    ],
  },
  {
    id: 'biz-pharmacie',
    name: 'Pharmacie Centrale de l’Étoile',
    moduleCode: 'PHARMACIE',
    categoryName: 'Pharmacies & Officines',
    neighborhood: 'Cadjehoun',
    city: 'Cotonou',
    distanceKm: 1.3,
    rating: 4.8,
    reviewCount: 95,
    isVerified: true,
    isOpenNow: true,
    openHoursText: 'Ouvert 24h/24 · Service de garde',
    phone: '+229 21 30 11 22',
    whatsapp: '+229 21 30 11 22',
    coverImage: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&q=80',
    description: 'Officine de garde à Cotonou. Disponibilité en direct des produits officinaux, permanence de nuit, localisation et contact rapide.',
    priceStartingAt: 1000,
    priceUnitText: 'le produit',
    badgeStatus: 'Pharmacie de garde',
    bookingType: 'visite',
    services: [
      {
        id: 'svc-ph1',
        title: 'Service de garde 24h/24',
        subtitle: 'Permanence de nuit et week-end assurée',
        price: 0,
        priceFormatted: 'Accès libre',
        isAvailable: true,
      },
      {
        id: 'svc-ph2',
        title: 'Vérification disponibilité produit & retrait',
        subtitle: 'Contact direct officine pour confirmation stock',
        price: 0,
        priceFormatted: 'Contact direct',
        isAvailable: true,
      },
    ],
    offers: [],
    photos: [
      'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&q=80',
    ],
    reviews: [
      {
        id: 'rev-ph1',
        author: 'Sylvie',
        avatarColor: '#0794A0',
        rating: 5,
        date: 'hier',
        comment: 'Pharmacie ouverte tard la nuit, personnel serviable et produits disponibles.',
      },
    ],
  },
];

export const ON_DUTY_PHARMACIES = [
  {
    id: 'ph-1',
    name: 'Pharmacie de garde — Cadjehoun',
    district: 'Cadjehoun (près du carrefour des 3 banques)',
    distanceKm: 2.1,
    isOpen: true,
    phone: '+229 21 30 11 22',
  },
  {
    id: 'ph-2',
    name: 'Pharmacie de garde — Fidjrossè',
    district: 'Fidjrossè Pavé (face station)',
    distanceKm: 3.8,
    isOpen: true,
    phone: '+229 21 30 44 55',
  },
  {
    id: 'ph-3',
    name: 'Pharmacie de garde — Akpakpa',
    district: 'Akpakpa Dodomè (route de Porto-Novo)',
    distanceKm: 6.4,
    isOpen: true,
    phone: '+229 21 33 77 88',
  },
];
