# Generated by Django 5.2.17 on 2026-09-03 15:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date et heure de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification')),
                ('target', models.CharField(db_index=True, max_length=255, verbose_name='Cible (email ou téléphone)')),
                ('otp_type', models.CharField(choices=[('EMAIL_VERIFICATION', "Vérification d'email"), ('PHONE_VERIFICATION', 'Vérification de téléphone'), ('PASSWORD_RESET', 'Réinitialisation mot de passe'), ('LOGIN_2FA', 'Double facteur de connexion')], db_index=True, max_length=30, verbose_name='Type OTP')),
                ('code', models.CharField(max_length=10, verbose_name='Code OTP')),
                ('is_used', models.BooleanField(default=False, verbose_name='Déjà utilisé')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name="Date d'expiration")),
            ],
            options={
                'verbose_name': 'Code OTP',
                'verbose_name_plural': 'Codes OTP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSecuritySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date et heure de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification')),
                ('refresh_token_jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('device_name', models.CharField(blank=True, max_length=255, verbose_name='Appareil identifié')),
                ('is_active', models.BooleanField(default=True, verbose_name='Session active')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière activité')),
            ],
            options={
                'verbose_name': 'Session de sécurité',
                'verbose_name_plural': 'Sessions de sécurité',
                'ordering': ['-last_activity'],
            },
        ),
    ]
