# Generated by Django 5.2.17 on 2026-09-03 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date et heure de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'entité est active")),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'organisation")),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Identifiant unique (slug)')),
                ('max_businesses', models.PositiveIntegerField(default=5, verbose_name="Nombre maximum d'entreprises autorisées")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_tenants', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire principal')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-created_at'],
            },
        ),
    ]
