# Generated by Django 5.2.17 on 2026-09-03 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date et heure de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'entité est active")),
                ('name', models.CharField(max_length=255, verbose_name='Nom commercial')),
                ('slug', models.SlugField(max_length=120, verbose_name='Identifiant')),
                ('module_code', models.CharField(choices=[('IMMOBILIER', 'Immobilier'), ('GUEST_HOUSE', 'Guest House'), ('COIFFURE', 'Coiffure'), ('BARBIER', 'Barbier'), ('INSTITUT_COSMETIQUE', 'Institut / Cosmétique'), ('SPA_MASSAGE', 'Spa / Massage'), ('PHOTOGRAPHE', 'Photographe'), ('BRODERIE_IMPRESSION', 'Broderie / Impression'), ('GARAGE', 'Garage'), ('PHARMACIE', 'Pharmacie')], db_index=True, max_length=40, verbose_name='Module métier')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse physique')),
                ('city', models.CharField(default='Cotonou', max_length=100, verbose_name='Ville')),
                ('country', models.CharField(default='Bénin', max_length=100, verbose_name='Pays')),
                ('currency', models.CharField(default='XOF', max_length=10, verbose_name='Devise')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Paramètres spécifiques')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='tenants.tenant', verbose_name='Organisation parente')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='BusinessMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date et heure de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Indique si l'entité est active")),
                ('role', models.CharField(choices=[('OWNER', 'Propriétaire'), ('MANAGER', 'Gérant / Manager'), ('EMPLOYEE', 'Employé')], db_index=True, default='EMPLOYEE', max_length=20, verbose_name="Rôle dans l'entreprise")),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'intégration")),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='businesses.business', verbose_name='Entreprise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Membre d'entreprise",
                'verbose_name_plural': "Membres d'entreprise",
                'ordering': ['-joined_at'],
                'unique_together': {('business', 'user')},
            },
        ),
    ]
