# Generated by Django 5.2.17 on 2026-09-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='business',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list, verbose_name='Modules métiers activés'),
        ),
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='business_logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='business',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict, verbose_name="Horaires d'ouverture"),
        ),
        migrations.AddField(
            model_name='business',
            name='social_media',
            field=models.JSONField(blank=True, default=dict, verbose_name='Réseaux sociaux'),
        ),
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de validation'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('CLOSED', 'Fermé définitivement')], db_index=True, default='ACTIVE', max_length=20, verbose_name="Statut de l'entreprise"),
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site internet'),
        ),
        migrations.AlterField(
            model_name='business',
            name='module_code',
            field=models.CharField(choices=[('IMMOBILIER', 'Immobilier'), ('GUEST_HOUSE', 'Guest House'), ('COIFFURE', 'Coiffure'), ('BARBIER', 'Barbier'), ('INSTITUT_COSMETIQUE', 'Institut / Cosmétique'), ('SPA_MASSAGE', 'Spa / Massage'), ('PHOTOGRAPHE', 'Photographe'), ('BRODERIE_IMPRESSION', 'Broderie / Impression'), ('GARAGE', 'Garage'), ('PHARMACIE', 'Pharmacie')], db_index=True, max_length=40, verbose_name='Module métier principal'),
        ),
    ]
