# Generated by Django 5.2.17 on 2026-09-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_description_business_enabled_modules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, verbose_name='Identifiant'),
        ),
    ]
